on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # ----- rust -----
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ hashFiles('./bq2cst/Cargo.lock') }}
          # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/db
      - run: make build
        working-directory: ./bq2cst

      # ----- typescript -----
      # since packageManager is specified in package.json, any pnpm version is OK
      - run: mkdir -p bq2cst/{cjs,esm}
      - run: npm install -g pnpm
      - &setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm install
      - run: pnpm --recursive run build

      # ----- upload -----
      # see https://github.com/actions/starter-workflows/blob/main/pages/static.yml
      # see https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: "./web/dist"
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with: &artifact-bq2cst-cjs
          name: bq2cst-cjs
          path: ./bq2cst/cjs
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with: &artifact-bq2cst-esm
          name: bq2cst-esm
          path: ./bq2cst/esm
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with: &artifact-prettier-plugin-bq
          name: prettier-plugin-bq
          path: ./prettier-plugin-bq/dist

      # ----- test -----
      - run: pnpm run test

  deploy-pkg:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      #  always pass when ref_type == 'branch'
      - uses: kitta65/tag-version-match@main
        with:
          file: ./prettier-plugin-bq/package.json
          query: .version
          pattern: '^([0-9]+\.[0-9]+\.[0-9]+)$'
      - uses: kitta65/tag-version-match@main
        with:
          file: ./bq2cst/Cargo.toml
          query: .package.version
          pattern: '^([0-9]+\.[0-9]+\.[0-9]+)$'
      - run: npm install -g pnpm
      - *setup-node
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with: *artifact-bq2cst-cjs
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with: *artifact-bq2cst-esm
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with: *artifact-prettier-plugin-bq
      # needed to resolve workspace protocol of dependency "bq2cst"
      - run: pnpm install
      - run: pnpm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-page:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - id: deployment
        if: ${{ github.ref_type == 'tag' }}
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
